id = "haproxy"
name = "haproxy"
version = "0.0.1"
schema_version = 1
authors = ["Denys Miasnychenko <jtsunne@gmail.com>"]
description = "HAproxy support"
repository = "https://github.com/jtsunne/zed-haproxy"

[grammars.haproxy]
repository = "https://github.com/jtsunne/tree-sitter-haproxy"
commit = "562dcab527d9f51800edfc08d6b9d3bbb9ae8b32"
