id = "haproxy"
name = "haproxy"
version = "0.4.0"
schema_version = 1
authors = ["Denys Miasnychenko <jtsunne@gmail.com>"]
description = "HAproxy support"
repository = "https://github.com/jtsunne/zed-haproxy"

[grammars.haproxy]
repository = "https://github.com/jtsunne/tree-sitter-haproxy"
commit = "ef605151993ff0128eeb9fcb3af8035ae8b0d82c"

[language_servers.haproxy-lsp]
name = "haproxy-lsp"
language = "haproxy"
