id = "haproxy"
name = "haproxy"
version = "0.0.6"
schema_version = 1
authors = ["Denys Miasnychenko <jtsunne@gmail.com>"]
description = "HAproxy support"
repository = "https://github.com/jtsunne/zed-haproxy"

[grammars.haproxy]
repository = "https://github.com/Ziehnert/tree-sitter-haproxy"
commit = "c20926a1613b1a0f923a114761ace3e9f6be9bd4"
